console.log('=== ADMIN USER CREATION INSTRUCTIONS ===');
console.log('');
console.log('To create the admin user, you need to:');
console.log('');
console.log('1. Go to Firebase Console: https://console.firebase.google.com/project/toolntask/authentication/users');
console.log('2. Click "Add User"');
console.log('3. Use these credentials:');
console.log('   Email: admin@toolntask.com');
console.log('   Password: AdminToolnTask2025!');
console.log('');
console.log('4. After creating, go to Firestore Database');
console.log('5. Create collection "users" if it doesn\'t exist');
console.log('6. Add document with ID matching the user UID:');
console.log('   {');
console.log('     email: "admin@toolntask.com",');
console.log('     role: "admin",');
console.log('     firstName: "Admin",');
console.log('     lastName: "User",');
console.log('     createdAt: new Date()');
console.log('   }');
console.log('');
console.log('7. CREATE FIREBASE INDEX for tasks:');
console.log('   Go to: https://console.firebase.google.com/project/toolntask/firestore/indexes');
console.log('   Add composite index for collection "tasks" with fields:');
console.log('   - userId (Ascending)');
console.log('   - createdAt (Descending)');
console.log('   - __name__ (Descending)');
console.log('');
console.log('   OR use this direct link from the error:');
console.log('   https://console.firebase.google.com/v1/r/project/toolntask/firestore/indexes?create_composite=Ckdwcm9qZWN0cy90b29sbnRhc2svZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL3Rhc2tzL2luZGV4ZXMvXxABGgoKBnVzZXJJZBABGg0KCWNyZWF0ZWRBdBACGgwKCF9fbmFtZV9fEAI');
console.log('');
console.log('=== ADMIN CREDENTIALS ===');
console.log('Email: admin@toolntask.com');
console.log('Password: AdminToolnTask2025!');
console.log('==============================');
